Name:           ros-indigo-pr2-controller-configuration-gazebo
Version:        2.0.7
Release:        0%{?dist}
Summary:        ROS pr2_controller_configuration_gazebo package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_controller_configuration_gazebo
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-pr2-controller-manager
Requires:       ros-indigo-pr2-gripper-action
Requires:       ros-indigo-pr2-head-action
Requires:       ros-indigo-single-joint-position-action
BuildRequires:  ros-indigo-catkin

%description
A copy of the pr2_controller_configuration package, for use in the PR2
simulator. We maintain two copies to allow for controller gains to be set
differently between hardware and simulation.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Dec 14 2015 John Hsu <hsu@osrfoundation.org> - 2.0.7-0
- Autogenerated by Bloom

* Tue Sep 01 2015 John Hsu <hsu@osrfoundation.org> - 2.0.6-0
- Autogenerated by Bloom

* Fri Mar 13 2015 John Hsu <hsu@osrfoundation.org> - 2.0.5-0
- Autogenerated by Bloom

* Wed Feb 11 2015 John Hsu <hsu@osrfoundation.org> - 2.0.4-1
- Autogenerated by Bloom

* Wed Feb 11 2015 John Hsu <hsu@osrfoundation.org> - 2.0.4-0
- Autogenerated by Bloom

